node{
    stage('build'){
        sh 'python3 -V'
    }
    stage('test'){
        git branch: 'main', url: 'https://https://github.com/MarBahlJR/as2-devops.git'
        sh 'python3 Hellopuc.py'
    }
    stage('deploy'){
        echo "finished"
    }
}
